module.exports = {
  TWILIO_ACCOUNT_SID: 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  TWILIO_AUTH_TOKEN: 'your_auth_token',
  TWILIO_TWIML_APP_SID: 'APXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  TWILIO_CALLER_ID: '+1XXXYYYZZZZ'
};
